### PR TITLE
fix(Local Storage) Catch and manage exception when local storage size is reached

### PR DESCRIPTION
**Pull request by bennekrouf**
"capacity" does not prevent from having a maximum size reached exception with the local storage.

Here, the idea is to catch this exception (around setItem), compute the size of the item that is provoking the exception. Then, removing from the cache oldest item until there are enough space for adding this new item.

### CODE REVIEW

**Comment by jmdobry** [comment]
I can't merge this PR, I think it needs to be updated with master.

**Comment by marlonpp** [comment]
+1 for this.
Could you explain how is the behavior when localStorage explodes?
Data will not be cached anymore? It will use memory?

**Comment by bennekrouf** [comment]
With this PR, if the max LS size is reached during a put, I remove 30% of the cache do the put. 

We can imaginate relying on memory in this case, but I think it's can confuse the user by having some data in memory (flushable by F5) and others in LS... only based on technical considerations.

**Comment by bdkent** [comment]
was this issue ever resolved?

**Comment by jmdobry** [comment]
@bdkent https://github.com/jmdobry/angular-cache/issues/180#issuecomment-159095766

**Pull request closed without merging**
